name: CI

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
        with:
          python-version: '3.12.0'
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure --color always
        env:
          SKIP: no-commit-to-branch,mypy

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      id-token: write
      pull-requests: write

    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb  # v3.3.0
      - name: Cache Docker layers
        uses: docker/bake-action@f6acc70fe0da9b200315017ca49a08c0de03aa0b  # v5.1.0
        with:
          targets: |
            tests
          push: false
          load: true
          files: |-
            docker-compose.yml
            docker-compose-cache.json
      - name: Run tests
        run: |
          docker compose run tests --junitxml=reports/junit.xml --cov=. --cov-branch --cov-report=term --cov-report=xml:reports/coverage.xml --cov-report=html:reports/coverage
      - name: Test Report
        uses: dorny/test-reporter@c40d89d5e987cd80f3a32b3c233556e22bdca958  # v1.9.0
        if: success() || failure()
        with:
          name: pytest results
          path: reports/junit.xml
          reporter: java-junit
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95  # v1.3.0
        with:
          filename: reports/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 90'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31  # v2.9.0
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
